### ISSUE TITLE
[Train] Use valid and train data to train model

### ISSUE THREAD

**Issue by jsdussanc** [tryolabs/luminoth#226]
Why only use a data bank to train the model, it has always been better to use a data bank for training and another for validation to avoid the over-training of the model, why not use it here?

**Comment by dekked** [comment]
Hello @jsdussanc!

When you use a dataset, you normally have several 'splits': `train`, `val` and `test`.

Using them appropriately is the responsibility of the user. For example, you would use `val` for hyperparameter tuning. The `lumi dataset` tool can convert several splits to tfrecords for using with Luminoth.

Please let me know if my answer suffices or if I did not understand your question!

**Comment by jsdussanc** [comment]
No, you have not understood me

It is true that many of the Luminoth tools support "split", but the training tool does not include this and you have to choose only one dataset for it.

See line 74 in luminoth/models/ssd/base_config.yml

``` yml
dataset:
  type: tfrecord
  # From which directory to read the dataset
  dir: datasets/voc/tf
  # Which split of tfrecords to look for
  split: train
```
Only support one split to train

In my feew knowledge, the "train" dataset is used to perform the backpropagation and the "valid" dataset to perform the tuning hyperparameter tuning or set the fitness for epoch.

Please correct me if I'm wrong about something or if I'm not very clear
