### ISSUE TITLE
constantly getting error "InvalidArgumentError (see above for traceback): Incompatible shapes: [0,4] vs. [7,4]"

### ISSUE THREAD

**Issue by Longbowman** [tryolabs/luminoth#276]
Hi

I am constantly getting certain errors. 
lumi train -c config.yml

this is config.file

```
train:
  # Name used to identify the run. Data inside `job_dir` will be stored under
  # `run_name`.
  run_name: table-area-detection-0.1
  # Base directory in which model checkpoints & summaries (for Tensorboard) will
  # be saved.
  job_dir: jobs/
  save_checkpoint_secs: 10
  save_summaries_secs: 10

  # Number of epochs (complete dataset batches) to run.
  num_epochs: 10

dataset:
  type: object_detection
  # From which directory to read the dataset.
  dir: tfdata/
  image_preprocessing:
    min_size: 600
    max_size: 1024
  data_augmentation:
    - flip:
        left_right: True
        up_down: True
        prob: 0.5

model:
  type: fasterrcnn
  network:
    # Total number of classes to predict.
    num_classes: 1

```

there is an error 
https://pastebin.com/wSLivh5Y

I tried 0.2.0-0.2.3 luminoth and 1.7.0-1.13.0 versions
