### ISSUE TITLE
Training Faster-RCNN using scientific data 

### ISSUE THREAD

**Issue by jiangzihanict** [tryolabs/luminoth#281]
We have a special dataset about extreme weather. The dataset has 16 channels and the size of the image is 1000*700px, which is totally different from the ImageNet. We want to implement end to end training based on this dataset.
The Faster-RCNN is composed of three parts: base network + RPN + RCNN. The base network usually is a pre-trained CNN(e.g. ResNet , VGG) for extracting features, but only ImageNet-based model can be found because our dataset is not common. So, the question is can I implement end to end training without a pre-trained base network? Or, does the end to end training of Faster-RCNN include the parameters in the base network?

**Comment by dekked** [comment]
Hello @jiangzihanict!

Even though data might be quite different from ImageNet, I would still advise you to start from the pre-trained model and not from scratch. Transfer learning is widely used because the learned features on one dataset can be good for many tasks, even using different datasets.

In Luminoth, the way to control whether you want to train the entire network or not is with the following configuration parameter in `config.yml`:

```yml
  base_network:
    # Starting point after which all the variables in the base network will be
    # trainable. If not specified, then all the variables in the network will be
    # trainable.
    fine_tune_from: block2
```

So, changing `block2` to an empty value will make it so that you train the entire network.

PD: I am curious, how does your data look like? Why did you pick Luminoth? :muscle:
